#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : qt-creator
Version  : 4.14.1
Release  : 51
URL      : file:///insilications/build/git-clr/qt-creator-clr.tar.gz
Source0  : file:///insilications/build/git-clr/qt-creator-clr.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0 LGPL-2.1
Requires: qt-creator-bin = %{version}-%{release}
Requires: qt-creator-data = %{version}-%{release}
Requires: qt-creator-lib = %{version}-%{release}
Requires: qt-creator-libexec = %{version}-%{release}
BuildRequires : ImageMagick-dev
BuildRequires : SDL2
BuildRequires : SDL2-dev
BuildRequires : SDL2-staticdev
BuildRequires : SVT-AV1-dev
BuildRequires : SVT-AV1-staticdev
BuildRequires : Sphinx
BuildRequires : Vulkan-Headers-dev
BuildRequires : Vulkan-Loader-dev
BuildRequires : Z3-dev
BuildRequires : Z3-staticdev
BuildRequires : acl
BuildRequires : acl-dev
BuildRequires : acl-staticdev
BuildRequires : alsa-lib-dev
BuildRequires : alsa-lib-lib
BuildRequires : alsa-tools
BuildRequires : binutils
BuildRequires : binutils-dev
BuildRequires : binutils-staticdev
BuildRequires : brotli
BuildRequires : brotli-dev
BuildRequires : brotli-staticdev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-meson
BuildRequires : buildreq-qmake
BuildRequires : bzip2
BuildRequires : bzip2-dev
BuildRequires : bzip2-staticdev
BuildRequires : cairo
BuildRequires : cairo-dev
BuildRequires : cairo-lib
BuildRequires : ccache
BuildRequires : clazy
BuildRequires : clazy-dev
BuildRequires : cmake
BuildRequires : cppcheck
BuildRequires : cuda
BuildRequires : cuda-dev
BuildRequires : cuda-lib
BuildRequires : cuda-plugins
BuildRequires : cuda-staticdev
BuildRequires : curl-dev
BuildRequires : curl-staticdev
BuildRequires : dbus-dev
BuildRequires : doxygen
BuildRequires : e2fsprogs-dev
BuildRequires : elfutils-dev
BuildRequires : evtest
BuildRequires : expat-dev
BuildRequires : expat-staticdev
BuildRequires : fftw-dev
BuildRequires : fftw-staticdev
BuildRequires : findutils
BuildRequires : flac
BuildRequires : flac-dev
BuildRequires : flac-staticdev
BuildRequires : fontconfig-data
BuildRequires : fontconfig-dev
BuildRequires : fontconfig-lib
BuildRequires : fontconfig-staticdev
BuildRequires : freetype-dev
BuildRequires : freetype-lib
BuildRequires : freetype-staticdev
BuildRequires : fribidi-dev
BuildRequires : fribidi-staticdev
BuildRequires : gcc-dev
BuildRequires : gdb
BuildRequires : gdb-dev
BuildRequires : glib
BuildRequires : glib-bin
BuildRequires : glib-data
BuildRequires : glib-dev
BuildRequires : glib-lib
BuildRequires : glibc
BuildRequires : glibc-dev
BuildRequires : glibc-staticdev
BuildRequires : gmp
BuildRequires : gmp-dev
BuildRequires : gmp-staticdev
BuildRequires : gnutls
BuildRequires : gnutls-dev
BuildRequires : graphite
BuildRequires : graphite-dev
BuildRequires : graphite-staticdev
BuildRequires : gsm-dev
BuildRequires : gsm-staticdev
BuildRequires : gtk+-data
BuildRequires : gtk+-lib
BuildRequires : gtk3-lib
BuildRequires : harfbuzz-dev
BuildRequires : harfbuzz-lib
BuildRequires : harfbuzz-staticdev
BuildRequires : icu4c-lib
BuildRequires : jsoncpp
BuildRequires : jsoncpp-dev
BuildRequires : jsoncpp-lib
BuildRequires : keyutils
BuildRequires : keyutils-dev
BuildRequires : krb5
BuildRequires : krb5-dev
BuildRequires : l-smash-dev
BuildRequires : l-smash-staticdev
BuildRequires : ladspa_sdk
BuildRequires : ladspa_sdk-bin
BuildRequires : ladspa_sdk-dev
BuildRequires : ladspa_sdk-lib
BuildRequires : ladspa_sdk-staticdev
BuildRequires : lcms2
BuildRequires : lcms2-dev
BuildRequires : lcms2-staticdev
BuildRequires : libX11-data
BuildRequires : libX11-dev
BuildRequires : libX11-lib
BuildRequires : libXScrnSaver
BuildRequires : libXScrnSaver-dev
BuildRequires : libXScrnSaver-lib
BuildRequires : libXau-dev
BuildRequires : libXau-lib
BuildRequires : libXcursor-dev
BuildRequires : libXcursor-lib
BuildRequires : libXdamage-dev
BuildRequires : libXdamage-lib
BuildRequires : libXdmcp-dev
BuildRequires : libXdmcp-lib
BuildRequires : libXext-dev
BuildRequires : libXext-lib
BuildRequires : libXfont2-dev
BuildRequires : libXft-dev
BuildRequires : libXft-lib
BuildRequires : libXi-dev
BuildRequires : libXi-lib
BuildRequires : libXrender-dev
BuildRequires : libXrender-lib
BuildRequires : libXtst-dev
BuildRequires : libXtst-lib
BuildRequires : libXxf86vm-dev
BuildRequires : libXxf86vm-lib
BuildRequires : libaom
BuildRequires : libaom-dev
BuildRequires : libaom-staticdev
BuildRequires : libarchive
BuildRequires : libarchive-dev
BuildRequires : libarchive-staticdev
BuildRequires : libass-dev
BuildRequires : libass-lib
BuildRequires : libass-staticdev
BuildRequires : libatomic_ops-dev
BuildRequires : libatomic_ops-staticdev
BuildRequires : libbluray
BuildRequires : libbluray-dev
BuildRequires : libbluray-staticdev
BuildRequires : libcap
BuildRequires : libcap-dev
BuildRequires : libcap-ng-dev
BuildRequires : libconfig-dev
BuildRequires : libconfig-staticdev
BuildRequires : libdav1d
BuildRequires : libdav1d-dev
BuildRequires : libdav1d-staticdev
BuildRequires : libdrm
BuildRequires : libdrm-dev
BuildRequires : libdrm-lib
BuildRequires : libdrm-staticdev
BuildRequires : libdvdnav
BuildRequires : libdvdnav-dev
BuildRequires : libdvdnav-staticdev
BuildRequires : libdvdread
BuildRequires : libdvdread-dev
BuildRequires : libdvdread-staticdev
BuildRequires : libedit
BuildRequires : libedit-dev
BuildRequires : libepoxy
BuildRequires : libepoxy-dev
BuildRequires : libfdk_aac
BuildRequires : libfdk_aac-dev
BuildRequires : libfdk_aac-staticdev
BuildRequires : libffi
BuildRequires : libffi-dev
BuildRequires : libffi-staticdev
BuildRequires : libgcrypt
BuildRequires : libgcrypt-dev
BuildRequires : libgpg-error
BuildRequires : libgpg-error-dev
BuildRequires : libidn2
BuildRequires : libidn2-dev
BuildRequires : libidn2-staticdev
BuildRequires : libinput-data
BuildRequires : libinput-lib
BuildRequires : libinput-libexec
BuildRequires : libjpeg-turbo-dev
BuildRequires : libjpeg-turbo-staticdev
BuildRequires : libmp3lame-dev
BuildRequires : libmp3lame-lib
BuildRequires : libmp3lame-staticdev
BuildRequires : libogg
BuildRequires : libogg-dev
BuildRequires : libogg-staticdev
BuildRequires : libpciaccess
BuildRequires : libpciaccess-dev
BuildRequires : libplacebo
BuildRequires : libplacebo-dev
BuildRequires : libplacebo-staticdev
BuildRequires : libpng-dev
BuildRequires : libpng-lib
BuildRequires : libpng-staticdev
BuildRequires : libsamplerate
BuildRequires : libsamplerate-dev
BuildRequires : libsamplerate-staticdev
BuildRequires : libsndfile
BuildRequires : libsndfile-dev
BuildRequires : libsndfile-staticdev
BuildRequires : libsrt-dev
BuildRequires : libsrt-staticdev
BuildRequires : libstdc++
BuildRequires : libstdc++-dev
BuildRequires : libtasn1-dev
BuildRequires : libtasn1-staticdev
BuildRequires : libtheora-dev
BuildRequires : libtheora-staticdev
BuildRequires : libudfread-dev
BuildRequires : libudfread-staticdev
BuildRequires : libunistring-dev
BuildRequires : libunistring-staticdev
BuildRequires : libunwind
BuildRequires : libunwind-dev
BuildRequires : libunwind-dev32
BuildRequires : libunwind-staticdev
BuildRequires : libunwind-staticdev32
BuildRequires : libusb
BuildRequires : libusb-dev
BuildRequires : libva
BuildRequires : libva-dev
BuildRequires : libva-lib
BuildRequires : libvdpau
BuildRequires : libvdpau-dev
BuildRequires : libvidstab-dev
BuildRequires : libvidstab-staticdev
BuildRequires : libvorbis
BuildRequires : libvorbis-dev
BuildRequires : libvorbis-staticdev
BuildRequires : libvpx
BuildRequires : libvpx-dev
BuildRequires : libvpx-staticdev
BuildRequires : libwebp-dev
BuildRequires : libwebp-staticdev
BuildRequires : libx264-dev
BuildRequires : libx264-staticdev
BuildRequires : libx265
BuildRequires : libx265-dev
BuildRequires : libx265-lib
BuildRequires : libx265-staticdev
BuildRequires : libxcb-dev
BuildRequires : libxcb-lib
BuildRequires : libxml2-dev
BuildRequires : libxml2-staticdev
BuildRequires : libxvid
BuildRequires : libxvid-dev
BuildRequires : libxvid-staticdev
BuildRequires : libzimg-dev
BuildRequires : libzimg-staticdev
BuildRequires : litehtml
BuildRequires : litehtml-dev
BuildRequires : llvm11
BuildRequires : llvm11-bin
BuildRequires : llvm11-data
BuildRequires : llvm11-dev
BuildRequires : llvm11-lib
BuildRequires : llvm11-libexec
BuildRequires : llvm11-staticdev
BuildRequires : lz4
BuildRequires : lz4-dev
BuildRequires : lz4-staticdev
BuildRequires : lzo
BuildRequires : lzo-dev
BuildRequires : lzo-staticdev
BuildRequires : md4c
BuildRequires : md4c-dev
BuildRequires : md4c-staticdev
BuildRequires : mediasdk-dev
BuildRequires : mesa
BuildRequires : mesa-dev
BuildRequires : mesa-lib
BuildRequires : mm-common-dev
BuildRequires : nasm
BuildRequires : nasm-bin
BuildRequires : ncurses-dev
BuildRequires : nettle
BuildRequires : nettle-dev
BuildRequires : nettle-staticdev
BuildRequires : not-ffmpeg
BuildRequires : not-ffmpeg-dev
BuildRequires : numlockx
BuildRequires : nv-codec-headers
BuildRequires : nv-codec-headers-dev
BuildRequires : nvidia
BuildRequires : nvidia-dev
BuildRequires : nvidia-lib
BuildRequires : opencl-headers
BuildRequires : opencl-headers-dev
BuildRequires : openjpeg-dev
BuildRequires : openjpeg-staticdev
BuildRequires : openssl
BuildRequires : openssl-dev
BuildRequires : openssl-lib
BuildRequires : openssl-staticdev
BuildRequires : opus-dev
BuildRequires : opus-staticdev
BuildRequires : orc-dev
BuildRequires : orc-staticdev
BuildRequires : p11-kit
BuildRequires : p11-kit-dev
BuildRequires : pacrunner
BuildRequires : pacrunner-dev
BuildRequires : pango-lib
BuildRequires : pcre-dev
BuildRequires : pcre-staticdev
BuildRequires : perl
BuildRequires : perl-Config-General
BuildRequires : perl-Config-Tiny
BuildRequires : perl-Crypt-SSLeay
BuildRequires : perl-DBI
BuildRequires : perl-DateTime-TimeZone
BuildRequires : perl-Encode-Locale
BuildRequires : perl-Error
BuildRequires : perl-File-Listing
BuildRequires : perl-HTML-Parser
BuildRequires : perl-HTML-Tagset
BuildRequires : perl-HTTP-Cookies
BuildRequires : perl-HTTP-Date
BuildRequires : perl-HTTP-Message
BuildRequires : perl-HTTP-Negotiate
BuildRequires : perl-IO-HTML
BuildRequires : perl-LWP-MediaTypes
BuildRequires : perl-LWP-Protocol-https
BuildRequires : perl-Params-Validate
BuildRequires : perl-Test-Simple
BuildRequires : perl-Try-Tiny
BuildRequires : perl-URI
BuildRequires : perl-XML-NamespaceSupport
BuildRequires : perl-XML-Parser
BuildRequires : perl-libwww-perl
BuildRequires : perl-man
BuildRequires : pixman
BuildRequires : pixman-dev
BuildRequires : pixman-lib
BuildRequires : pixman-staticdev
BuildRequires : pkg-config
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(Qt5Concurrent)
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5DBus)
BuildRequires : pkgconfig(Qt5Designer)
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5Help)
BuildRequires : pkgconfig(Qt5Location)
BuildRequires : pkgconfig(Qt5Multimedia)
BuildRequires : pkgconfig(Qt5Network)
BuildRequires : pkgconfig(Qt5OpenGL)
BuildRequires : pkgconfig(Qt5Pdf)
BuildRequires : pkgconfig(Qt5PdfWidgets)
BuildRequires : pkgconfig(Qt5PrintSupport)
BuildRequires : pkgconfig(Qt5Qml)
BuildRequires : pkgconfig(Qt5Quick)
BuildRequires : pkgconfig(Qt5QuickControls2)
BuildRequires : pkgconfig(Qt5QuickTest)
BuildRequires : pkgconfig(Qt5QuickWidgets)
BuildRequires : pkgconfig(Qt5Script)
BuildRequires : pkgconfig(Qt5Sensors)
BuildRequires : pkgconfig(Qt5SerialPort)
BuildRequires : pkgconfig(Qt5Sql)
BuildRequires : pkgconfig(Qt5Svg)
BuildRequires : pkgconfig(Qt5Test)
BuildRequires : pkgconfig(Qt5WebChannel)
BuildRequires : pkgconfig(Qt5WebEngine)
BuildRequires : pkgconfig(Qt5WebEngineCore)
BuildRequires : pkgconfig(Qt5WebEngineWidgets)
BuildRequires : pkgconfig(Qt5WebSockets)
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : pkgconfig(Qt5X11Extras)
BuildRequires : pkgconfig(Qt5Xml)
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(alsa-topology)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(dri)
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(gbm)
BuildRequires : pkgconfig(gl)
BuildRequires : pkgconfig(glesv1_cm)
BuildRequires : pkgconfig(glesv2)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libpulse-simple)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(libunwind)
BuildRequires : pkgconfig(libunwind-coredump)
BuildRequires : pkgconfig(libunwind-generic)
BuildRequires : pkgconfig(libunwind-ptrace)
BuildRequires : pkgconfig(libunwind-setjmp)
BuildRequires : pkgconfig(libusb-1.0)
BuildRequires : pkgconfig(osmesa)
BuildRequires : pkgconfig(samplerate)
BuildRequires : pkgconfig(vulkan)
BuildRequires : pkgconfig(wayland-protocols)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xatracker)
BuildRequires : pkgconfig(xcursor)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xi)
BuildRequires : pkgconfig(xinerama)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : pkgconfig(xrandr)
BuildRequires : pkgconfig(xscrnsaver)
BuildRequires : pkgconfig(zlib)
BuildRequires : pulseaudio
BuildRequires : pulseaudio-dev
BuildRequires : python3
BuildRequires : python3-core
BuildRequires : python3-dev
BuildRequires : python3-staticdev
BuildRequires : qca-qt5
BuildRequires : qca-qt5-dev
BuildRequires : qt3d
BuildRequires : qt3d-dev
BuildRequires : qt5ct
BuildRequires : qtbase
BuildRequires : qtbase-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : qtcanvas3d
BuildRequires : qtdatavis3d
BuildRequires : qtdatavis3d-dev
BuildRequires : qtdeclarative
BuildRequires : qtdeclarative-dev
BuildRequires : qtgamepad
BuildRequires : qtgamepad-dev
BuildRequires : qtgraphicaleffects
BuildRequires : qtlocation
BuildRequires : qtlocation-dev
BuildRequires : qtmqtt
BuildRequires : qtmqtt-dev
BuildRequires : qtnetworkauth
BuildRequires : qtnetworkauth-dev
BuildRequires : qtquickcontrols
BuildRequires : qtquickcontrols2
BuildRequires : qtquickcontrols2-dev
BuildRequires : qtscript
BuildRequires : qtscript-dev
BuildRequires : qtscxml
BuildRequires : qtscxml-dev
BuildRequires : qtsensors
BuildRequires : qtsensors-dev
BuildRequires : qtserialbus
BuildRequires : qtserialbus-dev
BuildRequires : qtspeech
BuildRequires : qtspeech-dev
BuildRequires : qtsvg
BuildRequires : qtsvg-dev
BuildRequires : qttools
BuildRequires : qttools-dev
BuildRequires : qttranslations
BuildRequires : qtvirtualkeyboard
BuildRequires : qtvirtualkeyboard-dev
BuildRequires : qtwebchannel
BuildRequires : qtwebchannel-dev
BuildRequires : qtwebengine
BuildRequires : qtwebengine-dev
BuildRequires : qtx11extras
BuildRequires : qtx11extras-dev
BuildRequires : rtmpdump
BuildRequires : rtmpdump-dev
BuildRequires : rtmpdump-staticdev
BuildRequires : rubberband-dev
BuildRequires : rubberband-staticdev
BuildRequires : setxkbmap
BuildRequires : shaderc
BuildRequires : shaderc-dev
BuildRequires : shaderc-staticdev
BuildRequires : snappy-dev
BuildRequires : snappy-staticdev
BuildRequires : speex-dev
BuildRequires : speex-staticdev
BuildRequires : speexdsp-dev
BuildRequires : speexdsp-staticdev
BuildRequires : sqlite-autoconf
BuildRequires : sqlite-autoconf-dev
BuildRequires : sqlite-autoconf-staticdev
BuildRequires : syntax-highlighting
BuildRequires : syntax-highlighting-dev
BuildRequires : syntax-highlighting-lib
BuildRequires : systemd
BuildRequires : systemd-dev
BuildRequires : texinfo
BuildRequires : uchardet
BuildRequires : uchardet-dev
BuildRequires : uchardet-staticdev
BuildRequires : util-linux
BuildRequires : util-linux-dev
BuildRequires : util-linux-staticdev
BuildRequires : valgrind
BuildRequires : valgrind-dev
BuildRequires : vamp-sdk
BuildRequires : vamp-sdk-dev
BuildRequires : vamp-sdk-staticdev
BuildRequires : wayland
BuildRequires : weston
BuildRequires : wmctrl
BuildRequires : xauth
BuildRequires : xclip
BuildRequires : xdg-dbus-proxy
BuildRequires : xdg-desktop-portal
BuildRequires : xdg-desktop-portal-dev
BuildRequires : xdg-desktop-portal-gtk
BuildRequires : xdg-desktop-portal-kde
BuildRequires : xdg-user-dirs
BuildRequires : xdg-user-dirs-gtk
BuildRequires : xdg-utils
BuildRequires : xdotool
BuildRequires : xdpyinfo
BuildRequires : xf86-input-libinput
BuildRequires : xf86-video-amdgpu
BuildRequires : xf86-video-ati
BuildRequires : xf86-video-fbdev
BuildRequires : xf86-video-nouveau
BuildRequires : xf86-video-qxl
BuildRequires : xf86-video-vboxvideo
BuildRequires : xf86-video-vesa
BuildRequires : xf86-video-vmware
BuildRequires : xfontsel
BuildRequires : xhost
BuildRequires : xinit
BuildRequires : xinput
BuildRequires : xkbcomp
BuildRequires : xkeyboard-config
BuildRequires : xkill
BuildRequires : xmodmap
BuildRequires : xorg-server
BuildRequires : xorg-server-dev
BuildRequires : xorgproto
BuildRequires : xorgproto-dev
BuildRequires : xprop
BuildRequires : xrandr
BuildRequires : xrdb
BuildRequires : xrdp
BuildRequires : xrestop
BuildRequires : xscreensaver
BuildRequires : xsel
BuildRequires : xset
BuildRequires : xsetroot
BuildRequires : xvfb-run
BuildRequires : xwd
BuildRequires : xwininfo
BuildRequires : xz
BuildRequires : xz-dev
BuildRequires : xz-staticdev
BuildRequires : yaml-cpp
BuildRequires : yaml-cpp-dev
BuildRequires : zlib
BuildRequires : zlib-dev
BuildRequires : zlib-staticdev
BuildRequires : zstd-dev
BuildRequires : zstd-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Qt is provided with a powerful embedded scripting environment through the Qt Script
classes.

%package bin
Summary: bin components for the qt-creator package.
Group: Binaries
Requires: qt-creator-data = %{version}-%{release}
Requires: qt-creator-libexec = %{version}-%{release}

%description bin
bin components for the qt-creator package.


%package data
Summary: data components for the qt-creator package.
Group: Data

%description data
data components for the qt-creator package.


%package lib
Summary: lib components for the qt-creator package.
Group: Libraries
Requires: qt-creator-data = %{version}-%{release}
Requires: qt-creator-libexec = %{version}-%{release}

%description lib
lib components for the qt-creator package.


%package libexec
Summary: libexec components for the qt-creator package.
Group: Default

%description libexec
libexec components for the qt-creator package.


%prep
%setup -q -n qt-creator-clr
cd %{_builddir}/qt-creator-clr

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1616767960
unset LD_AS_NEEDED
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
## altflags_pgo content
## pgo generate
export PGO_GEN="-fprofile-generate=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-update=atomic -fprofile-arcs -ftest-coverage --coverage -fprofile-partial-training"
export CFLAGS_GENERATE="-ffast-math -std=c17 -O2 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -Wall -Wl,--no-as-needed -Wl,--enable-new-dtags -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fstack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -flto=16 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -fno-plt -ffat-lto-objects -fPIC $PGO_GEN"
export FCFLAGS_GENERATE="-ffast-math -O2 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -Wall -Wl,--no-as-needed -Wl,--enable-new-dtags -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fstack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -flto=16 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -fno-plt -ffat-lto-objects -fPIC $PGO_GEN"
export FFLAGS_GENERATE="-ffast-math -O2 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -Wall -Wl,--no-as-needed -Wl,--enable-new-dtags -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fstack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -flto=16 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -fno-plt -ffat-lto-objects -fPIC $PGO_GEN"
export CXXFLAGS_GENERATE="-ffast-math -std=c++17 -O2 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -Wall -Wl,--no-as-needed -Wl,--enable-new-dtags -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fstack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -flto=16 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -fno-plt -ffat-lto-objects -fPIC $PGO_GEN"
export LDFLAGS_GENERATE="-ffast-math -O2 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -Wall -Wl,--no-as-needed -Wl,--enable-new-dtags -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fstack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -flto=16 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -fno-plt -ffat-lto-objects -fPIC $PGO_GEN"
## pgo use
## -Wl,--build-id=sha1 -Wl,--hash-style=gnu -mtls-dialect=gnu2  -fno-stack-protector
## -static-libstdc++ -static-libgcc -pthread
## -pthread -lpthread
## -fipa-pta
export PGO_USE="-fprofile-use=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-correction -fprofile-partial-training"
export CFLAGS_USE="-ffast-math -std=c17 -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--no-as-needed -Wl,--enable-new-dtags -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fstack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -flto=16 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -fno-plt -ffat-lto-objects -fPIC $PGO_USE"
export FCFLAGS_USE="-ffast-math -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--no-as-needed -Wl,--enable-new-dtags -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fstack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -flto=16 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -fno-plt -ffat-lto-objects -fPIC $PGO_USE"
export FFLAGS_USE="-ffast-math -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--no-as-needed -Wl,--enable-new-dtags -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fstack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -flto=16 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -fno-plt -ffat-lto-objects -fPIC $PGO_USE"
export CXXFLAGS_USE="-ffast-math -std=c++17 -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--no-as-needed -Wl,--enable-new-dtags -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fstack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -flto=16 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -fno-plt -ffat-lto-objects -fPIC $PGO_USE"
export LDFLAGS_USE="-ffast-math -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--no-as-needed -Wl,--enable-new-dtags -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fstack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -flto=16 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -fno-plt -ffat-lto-objects -fPIC $PGO_USE"
#
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
unset CCACHE_DISABLE
export PATH="/usr/lib64/ccache/bin:$PATH"
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
export V=1
export VERBOSE=1
#
export DISPLAY=:0
export __GL_ALLOW_UNOFFICIAL_PROTOCOL=1
export __GL_SYNC_TO_VBLANK=0
export LANG=en_US.UTF-8
export XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg
export XDG_SEAT=seat0
export XDG_SESSION_TYPE=tty
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_CLASS=user
export XDG_VTNR=1
export XDG_SESSION_ID=1
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export KDE_SESSION_VERSION=5
export KDE_SESSION_UID=1000
export KDE_FULL_SESSION=true
export KDE_APPLICATIONS_AS_SCOPE=1
export VDPAU_DRIVER=nvidia
export LIBVA_DRIVER_NAME=vdpau
export LIBVA_DRIVERS_PATH=/usr/lib64/dri
export GTK_RC_FILES=/etc/gtk/gtkrc
export FONTCONFIG_PATH=/usr/share/defaults/fonts
## altflags_pgo end
if [ ! -f status.pgo ]; then
echo PGO Phase 1
export CFLAGS="${CFLAGS_GENERATE}"
export CXXFLAGS="${CXXFLAGS_GENERATE}"
export FFLAGS="${FFLAGS_GENERATE}"
export FCFLAGS="${FCFLAGS_GENERATE}"
export LDFLAGS="${LDFLAGS_GENERATE}"
%cmake .. -DCMAKE_BUILD_TYPE=Release \
-DCLANGTOOLING_LINK_CLANG_DYLIB=NO \
-DBUILD_CPLUSPLUS_TOOLS=ON \
-DSHOW_BUILD_DATE=ON \
-DWITH_DOCS:BOOL=OFF \
-DLITEHTML_UTF8:BOOL=OFF \
-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
-DCMAKE_INSTALL_BINDIR=bin \
-DCMAKE_INSTALL_LIBDIR=lib64 \
-DCMAKE_INSTALL_LIBEXECDIR=libexec \
-DCMAKE_PREFIX_PATH=/usr \
-DWITH_TESTS:BOOL=ON
make  %{?_smp_mflags}  -j12 V=1 VERBOSE=1
## ccache stats
ccache -s
## ccache stats

export DISPLAY=:0
export __GL_ALLOW_UNOFFICIAL_PROTOCOL=1
export __GL_SYNC_TO_VBLANK=0
export LANG=en_US.UTF-8
export XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg
export XDG_SEAT=seat0
export XDG_SESSION_TYPE=tty
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_CLASS=user
export XDG_VTNR=1
export XDG_SESSION_ID=1
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export KDE_SESSION_VERSION=5
export KDE_SESSION_UID=1000
export KDE_FULL_SESSION=true
export KDE_APPLICATIONS_AS_SCOPE=1
export VDPAU_DRIVER=nvidia
export LIBVA_DRIVER_NAME=vdpau
export LIBVA_DRIVERS_PATH=/usr/lib64/dri
export GTK_RC_FILES=/etc/gtk/gtkrc
export FONTCONFIG_PATH=/usr/share/defaults/fonts
export LD_LIBRARY_PATH="/builddir/build/BUILD/qt-creator-clr/clr-build/lib64:/builddir/build/BUILD/qt-creator-clr/clr-build/lib64/qtcreator:/builddir/build/BUILD/qt-creator-clr/clr-build/lib64/qtcreator/plugins:/usr/cuda/lib64:/usr/cuda/targets/x86_64-linux/lib:/usr/nvidia/lib64:/usr/nvidia/lib:/usr/nvidia/lib/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/lib64/dri:/usr/lib64/haswell:/usr/lib64:/usr/lib:/usr/share"
export PKG_CONFIG_PATH="/usr/lib64/pkgconfig:../"
export PATH="/builddir/build/BUILD/qt-creator-clr/clr-build/bin:/builddir/build/BUILD/qt-creator-clr/clr-build/libexec/qtcreator:/opt/nvidia/bin:/usr/bin/haswell:/usr/bin:/usr/sbin"
export $(dbus-launch)
ctest --parallel 16 -V --progress --timeout 100 || :
#/builddir/build/BUILD/qt-creator-clr/clr-build/bin/qtcreator -temporarycleansettings -settingspath /builddir/ -installsettingspath /builddir/ -pluginpath /builddir/build/BUILD/qt-creator-clr/clr-build/lib64/qtcreator/plugins -noload ClangCodeModel ClangFormat
/builddir/build/BUILD/qt-creator-clr/clr-build/bin/qtcreator -noload Help
find . -type f,l -not -name '*.gcno' -not -name 'status.pgo' -delete -print
echo USED > status.pgo
fi
if [ -f status.pgo ]; then
echo PGO Phase 2
export CFLAGS="${CFLAGS_USE}"
export CXXFLAGS="${CXXFLAGS_USE}"
export FFLAGS="${FFLAGS_USE}"
export FCFLAGS="${FCFLAGS_USE}"
export LDFLAGS="${LDFLAGS_USE}"
%cmake .. -DCMAKE_BUILD_TYPE=Release \
-DCLANGTOOLING_LINK_CLANG_DYLIB=NO \
-DBUILD_CPLUSPLUS_TOOLS=ON \
-DSHOW_BUILD_DATE=ON \
-DWITH_DOCS:BOOL=OFF \
-DLITEHTML_UTF8:BOOL=OFF \
-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
-DCMAKE_INSTALL_BINDIR=bin \
-DCMAKE_INSTALL_LIBDIR=lib64 \
-DCMAKE_INSTALL_LIBEXECDIR=libexec \
-DCMAKE_PREFIX_PATH=/usr \
-DWITH_TESTS:BOOL=OFF
make  %{?_smp_mflags}  -j12 V=1 VERBOSE=1
## ccache stats
ccache -s
## ccache stats
fi
popd

%install
export SOURCE_DATE_EPOCH=1616767960
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/

%files bin
%defattr(-,root,root,-)
/usr/bin/qbs
/usr/bin/qbs-config
/usr/bin/qbs-config-ui
/usr/bin/qbs-create-project
/usr/bin/qbs-setup-android
/usr/bin/qbs-setup-qt
/usr/bin/qbs-setup-toolchains
/usr/bin/qtcreator
/usr/bin/qtcreator.sh

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.qt-project.qtcreator.desktop
/usr/share/icons/hicolor/128x128/apps/QtProject-qtcreator.png
/usr/share/icons/hicolor/16x16/apps/QtProject-qtcreator.png
/usr/share/icons/hicolor/24x24/apps/QtProject-qtcreator.png
/usr/share/icons/hicolor/256x256/apps/QtProject-qtcreator.png
/usr/share/icons/hicolor/32x32/apps/QtProject-qtcreator.png
/usr/share/icons/hicolor/48x48/apps/QtProject-qtcreator.png
/usr/share/icons/hicolor/512x512/apps/QtProject-qtcreator.png
/usr/share/icons/hicolor/64x64/apps/QtProject-qtcreator.png
/usr/share/metainfo/org.qt-project.qtcreator.appdata.xml
/usr/share/qtcreator/android/sdk_definitions.json
/usr/share/qtcreator/cplusplus/examples/CMakeLists.txt
/usr/share/qtcreator/cplusplus/examples/clazy_example.cpp
/usr/share/qtcreator/cplusplus/examples/examples.pro
/usr/share/qtcreator/cplusplus/examples/icontest.cpp
/usr/share/qtcreator/cplusplus/examples/tidy_example.cpp
/usr/share/qtcreator/cplusplus/examples/tidy_example.h
/usr/share/qtcreator/cplusplus/wrappedMingwHeaders/float.h
/usr/share/qtcreator/cplusplus/wrappedQtHeaders/QtCore/qobjectdefs.h
/usr/share/qtcreator/debugger/.pylintrc
/usr/share/qtcreator/debugger/LICENSE.GPL3-EXCEPT
/usr/share/qtcreator/debugger/README.txt
/usr/share/qtcreator/debugger/boosttypes.py
/usr/share/qtcreator/debugger/cdbbridge.py
/usr/share/qtcreator/debugger/creatortypes.py
/usr/share/qtcreator/debugger/dumper.py
/usr/share/qtcreator/debugger/gdbbridge.py
/usr/share/qtcreator/debugger/gdbtracepoint.py
/usr/share/qtcreator/debugger/lldbbridge.py
/usr/share/qtcreator/debugger/misctypes.py
/usr/share/qtcreator/debugger/opencvtypes.py
/usr/share/qtcreator/debugger/pdbbridge.py
/usr/share/qtcreator/debugger/personaltypes.py
/usr/share/qtcreator/debugger/qttypes.py
/usr/share/qtcreator/debugger/setup.cfg
/usr/share/qtcreator/debugger/stdtypes.py
/usr/share/qtcreator/debugger/utils.py
/usr/share/qtcreator/externaltools/lrelease.xml
/usr/share/qtcreator/externaltools/lupdate.xml
/usr/share/qtcreator/externaltools/qmlscene.xml
/usr/share/qtcreator/externaltools/qmlviewer.xml
/usr/share/qtcreator/externaltools/vi.xml
/usr/share/qtcreator/fonts/SourceCodePro-Bold.ttf
/usr/share/qtcreator/fonts/SourceCodePro-It.ttf
/usr/share/qtcreator/fonts/SourceCodePro-Regular.ttf
/usr/share/qtcreator/fonts/SourceCodePro.txt
/usr/share/qtcreator/glsl/glsl_120.frag
/usr/share/qtcreator/glsl/glsl_120.vert
/usr/share/qtcreator/glsl/glsl_120_common.glsl
/usr/share/qtcreator/glsl/glsl_330.frag
/usr/share/qtcreator/glsl/glsl_330.vert
/usr/share/qtcreator/glsl/glsl_330_common.glsl
/usr/share/qtcreator/glsl/glsl_es_100.frag
/usr/share/qtcreator/glsl/glsl_es_100.vert
/usr/share/qtcreator/glsl/glsl_es_100_common.glsl
/usr/share/qtcreator/indexer_preincludes/QtCore/qconfig.h
/usr/share/qtcreator/indexer_preincludes/QtCore/qglobal.h
/usr/share/qtcreator/indexer_preincludes/qglobal.h
/usr/share/qtcreator/indexer_preincludes/windows.h
/usr/share/qtcreator/modeleditor/standard.def
/usr/share/qtcreator/package-manager/auto-setup.cmake
/usr/share/qtcreator/package-manager/conan.cmake
/usr/share/qtcreator/qbs/share/qbs/examples/app-and-lib/app-and-lib.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/app-and-lib/app/app.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/app-and-lib/app/main.cpp
/usr/share/qtcreator/qbs/share/qbs/examples/app-and-lib/lib/lib.cpp
/usr/share/qtcreator/qbs/share/qbs/examples/app-and-lib/lib/lib.h
/usr/share/qtcreator/qbs/share/qbs/examples/app-and-lib/lib/lib.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/at90can128olimex/at90can128olimex.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/at90can128olimex/redblink/README.md
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/at90can128olimex/redblink/gpio.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/at90can128olimex/redblink/gpio.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/at90can128olimex/redblink/main.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/at90can128olimex/redblink/redblink.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/baremetal.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cc2540usbdongle/cc2540usbdongle.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cc2540usbdongle/greenblink/README.md
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cc2540usbdongle/greenblink/gpio.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cc2540usbdongle/greenblink/gpio.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cc2540usbdongle/greenblink/greenblink.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cc2540usbdongle/greenblink/main.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cc2540usbdongle/greenblink/system.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cy7c68013a/cy7c68013a.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cy7c68013a/nes-gamepads/README.md
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cy7c68013a/nes-gamepads/core.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cy7c68013a/nes-gamepads/core.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cy7c68013a/nes-gamepads/defs.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cy7c68013a/nes-gamepads/gpio.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cy7c68013a/nes-gamepads/gpio.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cy7c68013a/nes-gamepads/hid.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cy7c68013a/nes-gamepads/hid.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cy7c68013a/nes-gamepads/hiddesc.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cy7c68013a/nes-gamepads/hidep0.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cy7c68013a/nes-gamepads/hidep1.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cy7c68013a/nes-gamepads/irqs.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cy7c68013a/nes-gamepads/main.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cy7c68013a/nes-gamepads/nes-gamepads.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cy7c68013a/nes-gamepads/regs.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cy7c68013a/nes-gamepads/usb.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/cy7c68013a/nes-gamepads/usb.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/esp8266/README.md
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/esp8266/access-point/access-point.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/esp8266/access-point/user_config.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/esp8266/access-point/user_main.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/esp8266/esp8266.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/esp8266/qbs/imports/Esp8266SdkProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/esp8266/qbs/modules/esp8266_sdk/Esp8266SdkModule.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/msp430f5529.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/nes-gamepads/README.md
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/nes-gamepads/gamepads.ld
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/nes-gamepads/gpio.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/nes-gamepads/gpio.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/nes-gamepads/hid.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/nes-gamepads/hiddesc.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/nes-gamepads/hidep0.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/nes-gamepads/hidep1.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/nes-gamepads/hwdefs.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/nes-gamepads/main.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/nes-gamepads/nes-gamepads.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/nes-gamepads/pmm.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/nes-gamepads/pmm.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/nes-gamepads/ucs.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/nes-gamepads/ucs.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/nes-gamepads/usb.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/nes-gamepads/usb.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/nes-gamepads/wdt_a.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/nes-gamepads/wdt_a.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/redblink/README.md
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/redblink/gpio.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/redblink/gpio.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/redblink/main.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/redblink/redblink.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/redblink/system.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/redblink/system.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10001/greenblink/README.md
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10001/greenblink/gcc/flash.ld
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10001/greenblink/gcc/startup.s
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10001/greenblink/gpio.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10001/greenblink/gpio.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10001/greenblink/greenblink.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10001/greenblink/iar/flash.icf
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10001/greenblink/iar/startup.s
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10001/greenblink/keil/flash.sct
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10001/greenblink/keil/startup.s
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10001/greenblink/main.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10001/greenblink/system.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10001/pca10001.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10040/greenblink/README.md
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10040/greenblink/gcc/flash.ld
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10040/greenblink/gcc/startup.s
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10040/greenblink/gpio.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10040/greenblink/gpio.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10040/greenblink/greenblink.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10040/greenblink/iar/flash.icf
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10040/greenblink/iar/startup.s
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10040/greenblink/keil/flash.sct
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10040/greenblink/keil/startup.s
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10040/greenblink/main.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10040/greenblink/system.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10040/pca10040.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f103/greenblink/README.md
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f103/greenblink/gcc/flash.ld
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f103/greenblink/gcc/startup.s
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f103/greenblink/gpio.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f103/greenblink/gpio.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f103/greenblink/greenblink.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f103/greenblink/iar/flash.icf
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f103/greenblink/iar/startup.s
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f103/greenblink/keil/flash.sct
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f103/greenblink/keil/startup.s
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f103/greenblink/main.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f103/greenblink/system.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f103/stm32f103.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f4discovery/blueblink/README.md
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f4discovery/blueblink/blueblink.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f4discovery/blueblink/gcc/flash.ld
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f4discovery/blueblink/gcc/startup.s
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f4discovery/blueblink/gpio.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f4discovery/blueblink/gpio.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f4discovery/blueblink/iar/flash.icf
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f4discovery/blueblink/iar/startup.s
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f4discovery/blueblink/keil/flash.sct
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f4discovery/blueblink/keil/startup.s
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f4discovery/blueblink/main.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f4discovery/blueblink/system.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f4discovery/stm32f4discovery.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm8s103f3/redblink/README.md
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm8s103f3/redblink/gpio.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm8s103f3/redblink/gpio.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm8s103f3/redblink/main.c
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm8s103f3/redblink/redblink.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm8s103f3/redblink/system.h
/usr/share/qtcreator/qbs/share/qbs/examples/baremetal/stm8s103f3/stm8s103f3.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/capnproto/addressbook_cpp/addressbook.capnp
/usr/share/qtcreator/qbs/share/qbs/examples/capnproto/addressbook_cpp/addressbook.cpp
/usr/share/qtcreator/qbs/share/qbs/examples/capnproto/addressbook_cpp/addressbook_cpp.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/capnproto/calculator_cpp/calculator-client.cpp
/usr/share/qtcreator/qbs/share/qbs/examples/capnproto/calculator_cpp/calculator-server.cpp
/usr/share/qtcreator/qbs/share/qbs/examples/capnproto/calculator_cpp/calculator.capnp
/usr/share/qtcreator/qbs/share/qbs/examples/capnproto/calculator_cpp/calculator_cpp.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication.xcodeproj/project.pbxproj
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/AppDelegate.h
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/AppDelegate.m
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/CocoaApplication-Info.plist
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/CocoaApplication-Prefix.pch
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/CocoaApplication.xcassets/AppIcon.appiconset/Contents.json
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/CocoaApplication.xcassets/AppIcon.appiconset/icon_128x128.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/CocoaApplication.xcassets/AppIcon.appiconset/icon_128x128@2x.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/CocoaApplication.xcassets/AppIcon.appiconset/icon_16x16.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/CocoaApplication.xcassets/AppIcon.appiconset/icon_16x16@2x.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/CocoaApplication.xcassets/AppIcon.appiconset/icon_256x256.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/CocoaApplication.xcassets/AppIcon.appiconset/icon_256x256@2x.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/CocoaApplication.xcassets/AppIcon.appiconset/icon_32x32.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/CocoaApplication.xcassets/AppIcon.appiconset/icon_32x32@2x.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/CocoaApplication.xcassets/AppIcon.appiconset/icon_512x512.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/CocoaApplication.xcassets/AppIcon.appiconset/icon_512x512@2x.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/background.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/background@2x.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/dmg.iconset/icon_128x128.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/dmg.iconset/icon_128x128@2x.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/dmg.iconset/icon_16x16.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/dmg.iconset/icon_16x16@2x.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/dmg.iconset/icon_256x256.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/dmg.iconset/icon_256x256@2x.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/dmg.iconset/icon_32x32.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/dmg.iconset/icon_32x32@2x.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/dmg.iconset/icon_512x512.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/dmg.iconset/icon_512x512@2x.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/en.lproj/Credits.rtf
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/en.lproj/InfoPlist.strings
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/en.lproj/LICENSE
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/en.lproj/MainMenu.xib
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/en_US.lproj/Credits.rtf
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/en_US.lproj/InfoPlist.strings
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/en_US.lproj/LICENSE
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/en_US.lproj/MainMenu.xib
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/CocoaApplication/main.m
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/app.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/cocoa-application.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-application/dmg.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-touch-application/CocoaTouchApplication.xcodeproj/project.pbxproj
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-touch-application/CocoaTouchApplication/AppDelegate.h
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-touch-application/CocoaTouchApplication/AppDelegate.m
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-touch-application/CocoaTouchApplication/CocoaTouchApplication-Info.plist
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-touch-application/CocoaTouchApplication/CocoaTouchApplication-Prefix.pch
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-touch-application/CocoaTouchApplication/Default-568h@2x.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-touch-application/CocoaTouchApplication/Default.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-touch-application/CocoaTouchApplication/Default@2x.png
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-touch-application/CocoaTouchApplication/DetailViewController.h
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-touch-application/CocoaTouchApplication/DetailViewController.m
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-touch-application/CocoaTouchApplication/MasterViewController.h
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-touch-application/CocoaTouchApplication/MasterViewController.m
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-touch-application/CocoaTouchApplication/en.lproj/DetailViewController_iPad.xib
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-touch-application/CocoaTouchApplication/en.lproj/DetailViewController_iPhone.xib
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-touch-application/CocoaTouchApplication/en.lproj/InfoPlist.strings
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-touch-application/CocoaTouchApplication/en.lproj/MasterViewController_iPad.xib
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-touch-application/CocoaTouchApplication/en.lproj/MasterViewController_iPhone.xib
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-touch-application/CocoaTouchApplication/main.m
/usr/share/qtcreator/qbs/share/qbs/examples/cocoa-touch-application/cocoa-touch-application.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/code-generator/code-generator.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/code-generator/hwgen.cpp
/usr/share/qtcreator/qbs/share/qbs/examples/collidingmice/collidingmice.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/collidingmice/images/cheese.jpg
/usr/share/qtcreator/qbs/share/qbs/examples/collidingmice/main.cpp
/usr/share/qtcreator/qbs/share/qbs/examples/collidingmice/mice.qrc
/usr/share/qtcreator/qbs/share/qbs/examples/collidingmice/mouse.cpp
/usr/share/qtcreator/qbs/share/qbs/examples/collidingmice/mouse.h
/usr/share/qtcreator/qbs/share/qbs/examples/compiled-qml/MainForm.ui.qml
/usr/share/qtcreator/qbs/share/qbs/examples/compiled-qml/cheese.jpg
/usr/share/qtcreator/qbs/share/qbs/examples/compiled-qml/compiled-qml.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/compiled-qml/main.cpp
/usr/share/qtcreator/qbs/share/qbs/examples/compiled-qml/main.qml
/usr/share/qtcreator/qbs/share/qbs/examples/compiled-qml/qml.qrc
/usr/share/qtcreator/qbs/share/qbs/examples/examples.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/grpc/client.cpp
/usr/share/qtcreator/qbs/share/qbs/examples/grpc/grpc.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/grpc/ping-pong-grpc.proto
/usr/share/qtcreator/qbs/share/qbs/examples/grpc/server.cpp
/usr/share/qtcreator/qbs/share/qbs/examples/helloworld-complex/helloworld-complex.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/helloworld-complex/src/foo.cpp
/usr/share/qtcreator/qbs/share/qbs/examples/helloworld-complex/src/foo.h
/usr/share/qtcreator/qbs/share/qbs/examples/helloworld-complex/src/main.cpp
/usr/share/qtcreator/qbs/share/qbs/examples/helloworld-complex/src/specialfeature.cpp
/usr/share/qtcreator/qbs/share/qbs/examples/helloworld-complex/src/specialfeature.h
/usr/share/qtcreator/qbs/share/qbs/examples/helloworld-minimal/helloworld-minimal.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/helloworld-minimal/main.cpp
/usr/share/qtcreator/qbs/share/qbs/examples/helloworld-qt/helloworld-qt.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/helloworld-qt/main.cpp
/usr/share/qtcreator/qbs/share/qbs/examples/install-bundle/MainMenu.xib
/usr/share/qtcreator/qbs/share/qbs/examples/install-bundle/Storyboard.storyboard
/usr/share/qtcreator/qbs/share/qbs/examples/install-bundle/assetcatalog1.xcassets/other.imageset/Contents.json
/usr/share/qtcreator/qbs/share/qbs/examples/install-bundle/assetcatalog1.xcassets/other.imageset/icon_16x16.png
/usr/share/qtcreator/qbs/share/qbs/examples/install-bundle/assetcatalog1.xcassets/other.imageset/icon_16x16@2x.png
/usr/share/qtcreator/qbs/share/qbs/examples/install-bundle/assetcatalog2.xcassets/other.imageset/Contents.json
/usr/share/qtcreator/qbs/share/qbs/examples/install-bundle/assetcatalog2.xcassets/other.imageset/icon_16x16.png
/usr/share/qtcreator/qbs/share/qbs/examples/install-bundle/assetcatalog2.xcassets/other.imageset/icon_16x16@2x.png
/usr/share/qtcreator/qbs/share/qbs/examples/install-bundle/coreutils.cpp
/usr/share/qtcreator/qbs/share/qbs/examples/install-bundle/coreutils.h
/usr/share/qtcreator/qbs/share/qbs/examples/install-bundle/install-bundle.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/install-bundle/main.cpp
/usr/share/qtcreator/qbs/share/qbs/examples/install-bundle/white.iconset/icon_16x16.png
/usr/share/qtcreator/qbs/share/qbs/examples/install-bundle/white.iconset/icon_16x16@2x.png
/usr/share/qtcreator/qbs/share/qbs/examples/protobuf/addressbook_cpp/README.md
/usr/share/qtcreator/qbs/share/qbs/examples/protobuf/addressbook_cpp/addressbook_cpp.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/protobuf/addressbook_cpp/main.cpp
/usr/share/qtcreator/qbs/share/qbs/examples/protobuf/addressbook_objc/README.md
/usr/share/qtcreator/qbs/share/qbs/examples/protobuf/addressbook_objc/addressbook_objc.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/protobuf/addressbook_objc/main.m
/usr/share/qtcreator/qbs/share/qbs/examples/protobuf/shared/addressbook.proto
/usr/share/qtcreator/qbs/share/qbs/examples/rpaths/main.cpp
/usr/share/qtcreator/qbs/share/qbs/examples/rpaths/objecta.cpp
/usr/share/qtcreator/qbs/share/qbs/examples/rpaths/objecta.h
/usr/share/qtcreator/qbs/share/qbs/examples/rpaths/objectb.cpp
/usr/share/qtcreator/qbs/share/qbs/examples/rpaths/objectb.h
/usr/share/qtcreator/qbs/share/qbs/examples/rpaths/rpaths.qbs
/usr/share/qtcreator/qbs/share/qbs/examples/rule/lorem_ipsum.txt
/usr/share/qtcreator/qbs/share/qbs/examples/rule/rule.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/BundleTools/bundle-tools.js
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/DarwinTools/darwin-tools.js
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/ModUtils/utils.js
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/PathTools/path-tools.js
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/AndroidNdkProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/AndroidSdkProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/BinaryProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/ClBinaryProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/ClangClBinaryProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/ClangClProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/ConanfileProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/FrameworkProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/GccBinaryProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/GccProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/GccVersionProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/IarProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/IcoUtilsVersionProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/IncludeProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/InnoSetupProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/JdkProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/JdkVersionProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/KeilProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/LibraryProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/MsvcProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/NodeJsProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/NpmProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/PathProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/PkgConfigProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/SdccProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/TypeScriptProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/WiXProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/XcodeLocationProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/XcodeProbe.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/path-probe.js
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/UnixUtils/unix-utils.js
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/WindowsUtils/windows-utils.js
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/AndroidApk.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/AppleApplicationDiskImage.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/AppleDiskImage.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/Application.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/ApplicationExtension.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/AutotestRunner.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/CppApplication.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/DynamicLibrary.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/InnoSetup.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/InstallPackage.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/JavaClassCollection.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/JavaJarFile.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/Library.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/LoadableModule.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/NSISSetup.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/NativeBinary.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/NetModule.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/NodeJSApplication.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/QtApplication.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/QtGuiApplication.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/StaticLibrary.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/WindowsInstallerPackage.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/WindowsSetupPackage.qbs
/usr/share/qtcreator/qbs/share/qbs/imports/qbs/base/XPCService.qbs
/usr/share/qtcreator/qbs/share/qbs/module-providers/Qt/provider.qbs
/usr/share/qtcreator/qbs/share/qbs/module-providers/Qt/setup-qt.js
/usr/share/qtcreator/qbs/share/qbs/module-providers/Qt/templates/QtModule.qbs
/usr/share/qtcreator/qbs/share/qbs/module-providers/Qt/templates/QtPlugin.qbs
/usr/share/qtcreator/qbs/share/qbs/module-providers/Qt/templates/android_support.qbs
/usr/share/qtcreator/qbs/share/qbs/module-providers/Qt/templates/core.qbs
/usr/share/qtcreator/qbs/share/qbs/module-providers/Qt/templates/dbus.js
/usr/share/qtcreator/qbs/share/qbs/module-providers/Qt/templates/dbus.qbs
/usr/share/qtcreator/qbs/share/qbs/module-providers/Qt/templates/gui.qbs
/usr/share/qtcreator/qbs/share/qbs/module-providers/Qt/templates/moc.js
/usr/share/qtcreator/qbs/share/qbs/module-providers/Qt/templates/module.qbs
/usr/share/qtcreator/qbs/share/qbs/module-providers/Qt/templates/plugin.qbs
/usr/share/qtcreator/qbs/share/qbs/module-providers/Qt/templates/plugin_support.qbs
/usr/share/qtcreator/qbs/share/qbs/module-providers/Qt/templates/qdoc.js
/usr/share/qtcreator/qbs/share/qbs/module-providers/Qt/templates/qml.js
/usr/share/qtcreator/qbs/share/qbs/module-providers/Qt/templates/qml.qbs
/usr/share/qtcreator/qbs/share/qbs/module-providers/Qt/templates/qmlcache.qbs
/usr/share/qtcreator/qbs/share/qbs/module-providers/Qt/templates/quick.js
/usr/share/qtcreator/qbs/share/qbs/module-providers/Qt/templates/quick.qbs
/usr/share/qtcreator/qbs/share/qbs/module-providers/Qt/templates/scxml.qbs
/usr/share/qtcreator/qbs/share/qbs/module-providers/__fallback/fallback.qbs
/usr/share/qtcreator/qbs/share/qbs/module-providers/__fallback/provider.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/Android/android-utils.js
/usr/share/qtcreator/qbs/share/qbs/modules/Android/ndk/ndk.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/Android/ndk/utils.js
/usr/share/qtcreator/qbs/share/qbs/modules/Android/sdk/sdk.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/Android/sdk/utils.js
/usr/share/qtcreator/qbs/share/qbs/modules/Exporter/pkgconfig/pkgconfig.js
/usr/share/qtcreator/qbs/share/qbs/modules/Exporter/pkgconfig/pkgconfig.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/Exporter/qbs/qbsexporter.js
/usr/share/qtcreator/qbs/share/qbs/modules/Exporter/qbs/qbsexporter.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/archiver/archiver.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/autotest/autotest.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/bundle/BundleModule.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/bundle/MacOSX-Package-Types.xcspec
/usr/share/qtcreator/qbs/share/qbs/modules/bundle/MacOSX-Product-Types.xcspec
/usr/share/qtcreator/qbs/share/qbs/modules/bundle/bundle.js
/usr/share/qtcreator/qbs/share/qbs/modules/capnproto/capnproto.js
/usr/share/qtcreator/qbs/share/qbs/modules/capnproto/capnprotobase.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/capnproto/cpp/capnprotocpp.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cli/CLIModule.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cli/cli.js
/usr/share/qtcreator/qbs/share/qbs/modules/cli/mono.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cli/windows-dotnet.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/CppModule.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/DarwinGCC.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/GenericGCC.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/LinuxGCC.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/MingwBaseModule.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/UnixGCC.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/android-gcc.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/cpp.js
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/darwin.js
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/freebsd-gcc.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/freebsd.js
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/gcc.js
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/iar.js
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/iar.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/ios-gcc.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/keil.js
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/keil.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/macos-gcc.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/msvc.js
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/qnx-qcc.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/sdcc.js
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/sdcc.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/setuprunenv.js
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/tvos-gcc.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/watchos-gcc.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/windows-clang-cl.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/windows-clang-mingw.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/windows-mingw.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/windows-msvc-base.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cpp/windows-msvc.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/cpufeatures/cpufeatures.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/dmg/DMGModule.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/dmg/dmg.js
/usr/share/qtcreator/qbs/share/qbs/modules/freedesktop/FreeDesktop.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/freedesktop/freedesktop.js
/usr/share/qtcreator/qbs/share/qbs/modules/ib/IBModule.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/ib/ib.js
/usr/share/qtcreator/qbs/share/qbs/modules/ico/IcoModule.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/ico/ico.js
/usr/share/qtcreator/qbs/share/qbs/modules/innosetup/InnoSetupModule.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/java/JavaModule.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/java/io/qt/qbs/Artifact.java
/usr/share/qtcreator/qbs/share/qbs/modules/java/io/qt/qbs/ArtifactListJsonWriter.java
/usr/share/qtcreator/qbs/share/qbs/modules/java/io/qt/qbs/ArtifactListWriter.java
/usr/share/qtcreator/qbs/share/qbs/modules/java/io/qt/qbs/tools/JavaCompilerScannerTool.java
/usr/share/qtcreator/qbs/share/qbs/modules/java/io/qt/qbs/tools/utils/JavaCompilerOptions.java
/usr/share/qtcreator/qbs/share/qbs/modules/java/io/qt/qbs/tools/utils/JavaCompilerScanner.java
/usr/share/qtcreator/qbs/share/qbs/modules/java/io/qt/qbs/tools/utils/NullFileObject.java
/usr/share/qtcreator/qbs/share/qbs/modules/java/utils.js
/usr/share/qtcreator/qbs/share/qbs/modules/lex_yacc/lexyacc.js
/usr/share/qtcreator/qbs/share/qbs/modules/lex_yacc/lexyacc.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/nodejs/NodeJS.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/nodejs/nodejs.js
/usr/share/qtcreator/qbs/share/qbs/modules/nsis/NSISModule.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/pkgconfig/pkgconfig.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/protobuf/cpp/protobufcpp.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/protobuf/nanopb/nanopb.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/protobuf/objc/protobufobjc.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/protobuf/protobuf.js
/usr/share/qtcreator/qbs/share/qbs/modules/protobuf/protobufbase.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/qbs/common.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/qnx/qnx.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/texttemplate/texttemplate.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/typescript/TypeScriptModule.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/typescript/qbs-tsc-scan/.gitignore
/usr/share/qtcreator/qbs/share/qbs/modules/typescript/qbs-tsc-scan/qbs-tsc-scan.ts
/usr/share/qtcreator/qbs/share/qbs/modules/typescript/typescript.js
/usr/share/qtcreator/qbs/share/qbs/modules/vcs/vcs-module.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/wix/WiXModule.qbs
/usr/share/qtcreator/qbs/share/qbs/modules/xcode/xcode.js
/usr/share/qtcreator/qbs/share/qbs/modules/xcode/xcode.qbs
/usr/share/qtcreator/qbs/share/qbs/python/biplist/__init__.py
/usr/share/qtcreator/qbs/share/qbs/python/dmgbuild/__init__.py
/usr/share/qtcreator/qbs/share/qbs/python/dmgbuild/badge.py
/usr/share/qtcreator/qbs/share/qbs/python/dmgbuild/colors.py
/usr/share/qtcreator/qbs/share/qbs/python/dmgbuild/core.py
/usr/share/qtcreator/qbs/share/qbs/python/dmgbuild/licensing.py
/usr/share/qtcreator/qbs/share/qbs/python/dmgbuild/resources.py
/usr/share/qtcreator/qbs/share/qbs/python/ds_store/__init__.py
/usr/share/qtcreator/qbs/share/qbs/python/ds_store/buddy.py
/usr/share/qtcreator/qbs/share/qbs/python/ds_store/store.py
/usr/share/qtcreator/qbs/share/qbs/python/mac_alias/__init__.py
/usr/share/qtcreator/qbs/share/qbs/python/mac_alias/alias.py
/usr/share/qtcreator/qbs/share/qbs/python/mac_alias/bookmark.py
/usr/share/qtcreator/qbs/share/qbs/python/mac_alias/osx.py
/usr/share/qtcreator/qbs/share/qbs/python/mac_alias/utils.py
/usr/share/qtcreator/qbs/share/qbs/qml-type-descriptions/qbs-bundle.json
/usr/share/qtcreator/qbs/share/qbs/qml-type-descriptions/qbs.qmltypes
/usr/share/qtcreator/qml-type-descriptions/builtins.qmltypes
/usr/share/qtcreator/qml-type-descriptions/qbs-base.qmltypes
/usr/share/qtcreator/qml-type-descriptions/qbs-bundle.json
/usr/share/qtcreator/qml-type-descriptions/qbs.qmltypes
/usr/share/qtcreator/qml-type-descriptions/qmlproject-bundle.json
/usr/share/qtcreator/qml-type-descriptions/qmlproject.qmltypes
/usr/share/qtcreator/qml-type-descriptions/qmlruntime.qmltypes
/usr/share/qtcreator/qml-type-descriptions/qmltypes-bundle.json
/usr/share/qtcreator/qml-type-descriptions/qt-labs-folderlistmodel.qmltypes
/usr/share/qtcreator/qml-type-descriptions/qt-labs-gestures.qmltypes
/usr/share/qtcreator/qml-type-descriptions/qt-labs-particles.qmltypes
/usr/share/qtcreator/qml-type-descriptions/qt5QtQuick2-bundle.json
/usr/share/qtcreator/qml-type-descriptions/qtmobility-connectivity.qmltypes
/usr/share/qtcreator/qml-type-descriptions/qtmobility-contacts.qmltypes
/usr/share/qtcreator/qml-type-descriptions/qtmobility-feedback.qmltypes
/usr/share/qtcreator/qml-type-descriptions/qtmobility-gallery.qmltypes
/usr/share/qtcreator/qml-type-descriptions/qtmobility-location.qmltypes
/usr/share/qtcreator/qml-type-descriptions/qtmobility-messaging.qmltypes
/usr/share/qtcreator/qml-type-descriptions/qtmobility-organizer.qmltypes
/usr/share/qtcreator/qml-type-descriptions/qtmobility-publishsubscribe.qmltypes
/usr/share/qtcreator/qml-type-descriptions/qtmobility-sensors.qmltypes
/usr/share/qtcreator/qml-type-descriptions/qtmobility-serviceframework.qmltypes
/usr/share/qtcreator/qml-type-descriptions/qtmobility-systeminfo.qmltypes
/usr/share/qtcreator/qml-type-descriptions/qtmultimediakit.qmltypes
/usr/share/qtcreator/qml-type-descriptions/qtwebkit.qmltypes
/usr/share/qtcreator/qml/qmlpuppet/commands/captureddatacommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/changeauxiliarycommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/changeauxiliarycommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/changebindingscommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/changebindingscommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/changefileurlcommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/changefileurlcommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/changeidscommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/changeidscommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/changelanguagecommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/changelanguagecommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/changenodesourcecommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/changenodesourcecommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/changepreviewimagesizecommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/changepreviewimagesizecommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/changeselectioncommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/changeselectioncommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/changestatecommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/changestatecommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/changevaluescommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/changevaluescommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/childrenchangedcommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/childrenchangedcommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/clearscenecommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/clearscenecommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/commands.pri
/usr/share/qtcreator/qml/qmlpuppet/commands/completecomponentcommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/completecomponentcommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/componentcompletedcommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/componentcompletedcommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/createinstancescommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/createinstancescommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/createscenecommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/createscenecommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/debugoutputcommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/debugoutputcommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/endpuppetcommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/endpuppetcommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/informationchangedcommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/informationchangedcommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/inputeventcommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/inputeventcommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/pixmapchangedcommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/pixmapchangedcommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/puppetalivecommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/puppetalivecommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/puppettocreatorcommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/puppettocreatorcommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/removeinstancescommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/removeinstancescommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/removepropertiescommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/removepropertiescommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/removesharedmemorycommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/removesharedmemorycommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/reparentinstancescommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/reparentinstancescommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/requestmodelnodepreviewimagecommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/requestmodelnodepreviewimagecommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/scenecreatedcommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/statepreviewimagechangedcommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/statepreviewimagechangedcommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/synchronizecommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/synchronizecommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/tokencommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/tokencommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/update3dviewstatecommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/update3dviewstatecommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/valueschangedcommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/valueschangedcommand.h
/usr/share/qtcreator/qml/qmlpuppet/commands/view3dactioncommand.cpp
/usr/share/qtcreator/qml/qmlpuppet/commands/view3dactioncommand.h
/usr/share/qtcreator/qml/qmlpuppet/container/addimportcontainer.cpp
/usr/share/qtcreator/qml/qmlpuppet/container/addimportcontainer.h
/usr/share/qtcreator/qml/qmlpuppet/container/container.pri
/usr/share/qtcreator/qml/qmlpuppet/container/idcontainer.cpp
/usr/share/qtcreator/qml/qmlpuppet/container/idcontainer.h
/usr/share/qtcreator/qml/qmlpuppet/container/imagecontainer.cpp
/usr/share/qtcreator/qml/qmlpuppet/container/imagecontainer.h
/usr/share/qtcreator/qml/qmlpuppet/container/informationcontainer.cpp
/usr/share/qtcreator/qml/qmlpuppet/container/informationcontainer.h
/usr/share/qtcreator/qml/qmlpuppet/container/instancecontainer.cpp
/usr/share/qtcreator/qml/qmlpuppet/container/instancecontainer.h
/usr/share/qtcreator/qml/qmlpuppet/container/mockuptypecontainer.cpp
/usr/share/qtcreator/qml/qmlpuppet/container/mockuptypecontainer.h
/usr/share/qtcreator/qml/qmlpuppet/container/propertyabstractcontainer.cpp
/usr/share/qtcreator/qml/qmlpuppet/container/propertyabstractcontainer.h
/usr/share/qtcreator/qml/qmlpuppet/container/propertybindingcontainer.cpp
/usr/share/qtcreator/qml/qmlpuppet/container/propertybindingcontainer.h
/usr/share/qtcreator/qml/qmlpuppet/container/propertyvaluecontainer.cpp
/usr/share/qtcreator/qml/qmlpuppet/container/propertyvaluecontainer.h
/usr/share/qtcreator/qml/qmlpuppet/container/reparentcontainer.cpp
/usr/share/qtcreator/qml/qmlpuppet/container/reparentcontainer.h
/usr/share/qtcreator/qml/qmlpuppet/container/sharedmemory.h
/usr/share/qtcreator/qml/qmlpuppet/container/sharedmemory_qt.cpp
/usr/share/qtcreator/qml/qmlpuppet/container/sharedmemory_unix.cpp
/usr/share/qtcreator/qml/qmlpuppet/html/welcome.html
/usr/share/qtcreator/qml/qmlpuppet/images/non-visual-component.png
/usr/share/qtcreator/qml/qmlpuppet/images/non-visual-component@2x.png
/usr/share/qtcreator/qml/qmlpuppet/images/template_image.png
/usr/share/qtcreator/qml/qmlpuppet/images/webkit.png
/usr/share/qtcreator/qml/qmlpuppet/instances/instances.pri
/usr/share/qtcreator/qml/qmlpuppet/instances/nodeinstanceclientproxy.cpp
/usr/share/qtcreator/qml/qmlpuppet/instances/nodeinstanceclientproxy.h
/usr/share/qtcreator/qml/qmlpuppet/interfaces/commondefines.h
/usr/share/qtcreator/qml/qmlpuppet/interfaces/interfaces.pri
/usr/share/qtcreator/qml/qmlpuppet/interfaces/nodeinstanceclientinterface.h
/usr/share/qtcreator/qml/qmlpuppet/interfaces/nodeinstanceglobal.h
/usr/share/qtcreator/qml/qmlpuppet/interfaces/nodeinstanceserverinterface.cpp
/usr/share/qtcreator/qml/qmlpuppet/interfaces/nodeinstanceserverinterface.h
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/AdjustableArrow.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/AreaLightHandle.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/Arrow.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/AutoScaleHelper.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/AxisHelper.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/AxisHelperArm.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/CameraFrustum.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/CameraGizmo.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/Dialog.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/DirectionalDraggable.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/EditCameraController.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/EditView3D.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/FadeHandle.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/GenericBackend.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/HelperGrid.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/IconGizmo.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/IconRenderer3D.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/LightGizmo.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/LightIconGizmo.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/LightModel.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/Line3D.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/MaterialNodeView.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/ModelNode2DImageView.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/ModelNode3DImageView.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/ModelNodeView.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/MoveGizmo.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/NodeNodeView.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/Overlay2D.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/PlanarDraggable.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/PlanarMoveHandle.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/PlanarScaleHandle.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/RotateGizmo.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/RotateRing.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/ScaleGizmo.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/ScaleRod.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/SceneView3D.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/SelectionBox.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/SpotLightHandle.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/SwipeView.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/ToggleButton.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/ToolBarButton.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/Window.qml
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/images/area.png
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/images/area@2x.png
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/images/directional.png
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/images/directional@2x.png
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/images/editor_camera.png
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/images/editor_camera@2x.png
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/images/point.png
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/images/point@2x.png
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/images/spot.png
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/images/spot@2x.png
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/meshes/arrow.mesh
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/meshes/axishelper.mesh
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/meshes/ring.mesh
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/meshes/ringselect.mesh
/usr/share/qtcreator/qml/qmlpuppet/mockfiles/meshes/scalerod.mesh
/usr/share/qtcreator/qml/qmlpuppet/qml2puppet/Info.plist
/usr/share/qtcreator/qml/qmlpuppet/qml2puppet/editor3d/camerageometry.cpp
/usr/share/qtcreator/qml/qmlpuppet/qml2puppet/editor3d/camerageometry.h
/usr/share/qtcreator/qml/qmlpuppet/qml2puppet/editor3d/editor3d.pri
/usr/share/qtcreator/qml/qmlpuppet/qml2puppet/editor3d/generalhelper.cpp
/usr/share/qtcreator/qml/qmlpuppet/qml2puppet/editor3d/generalhelper.h
/usr/share/qtcreator/qml/qmlpuppet/qml2puppet/editor3d/gridgeometry.cpp
/usr/share/qtcreator/qml/qmlpuppet/qml2puppet/editor3d/gridgeometry.h
/usr/share/qtcreator/qml/qmlpuppet/qml2puppet/editor3d/icongizmoimageprovider.cpp
/usr/share/qtcreator/qml/qmlpuppet/qml2puppet/editor3d/icongizmoimageprovider.h
/usr/share/qtcreator/qml/qmlpuppet/qml2puppet/editor3d/lightgeometry.cpp
/usr/share/qtcreator/qml/qmlpuppet/qml2puppet/editor3d/lightgeometry.h

%files lib
%defattr(-,root,root,-)
/usr/lib64/qtcreator/libAdvancedDockingSystem.so.4
/usr/lib64/qtcreator/libAdvancedDockingSystem.so.4.15.82
/usr/lib64/qtcreator/libAggregation.so.4
/usr/lib64/qtcreator/libAggregation.so.4.15.82
/usr/lib64/qtcreator/libCPlusPlus.so.4
/usr/lib64/qtcreator/libCPlusPlus.so.4.15.82
/usr/lib64/qtcreator/libExtensionSystem.so.4
/usr/lib64/qtcreator/libExtensionSystem.so.4.15.82
/usr/lib64/qtcreator/libGLSL.so.4
/usr/lib64/qtcreator/libGLSL.so.4.15.82
/usr/lib64/qtcreator/libLanguageServerProtocol.so.4
/usr/lib64/qtcreator/libLanguageServerProtocol.so.4.15.82
/usr/lib64/qtcreator/libLanguageUtils.so.4
/usr/lib64/qtcreator/libLanguageUtils.so.4.15.82
/usr/lib64/qtcreator/libModeling.so.4
/usr/lib64/qtcreator/libModeling.so.4.15.82
/usr/lib64/qtcreator/libProParser.so.4
/usr/lib64/qtcreator/libProParser.so.4.15.82
/usr/lib64/qtcreator/libQmlDebug.so.4
/usr/lib64/qtcreator/libQmlDebug.so.4.15.82
/usr/lib64/qtcreator/libQmlEditorWidgets.so.4
/usr/lib64/qtcreator/libQmlEditorWidgets.so.4.15.82
/usr/lib64/qtcreator/libQmlJS.so.4
/usr/lib64/qtcreator/libQmlJS.so.4.15.82
/usr/lib64/qtcreator/libQtcSsh.so.4
/usr/lib64/qtcreator/libQtcSsh.so.4.15.82
/usr/lib64/qtcreator/libSqlite.so.4
/usr/lib64/qtcreator/libSqlite.so.4.15.82
/usr/lib64/qtcreator/libTracing.so.4
/usr/lib64/qtcreator/libTracing.so.4.15.82
/usr/lib64/qtcreator/libUtils.so.4
/usr/lib64/qtcreator/libUtils.so.4.15.82
/usr/lib64/qtcreator/libqbscore.so
/usr/lib64/qtcreator/libqbscore.so.1.18.2
/usr/lib64/qtcreator/libqlitehtml.so.4
/usr/lib64/qtcreator/libqlitehtml.so.4.15.82
/usr/lib64/qtcreator/plugins/libAndroid.so
/usr/lib64/qtcreator/plugins/libAutoTest.so
/usr/lib64/qtcreator/plugins/libAutotoolsProjectManager.so
/usr/lib64/qtcreator/plugins/libBareMetal.so
/usr/lib64/qtcreator/plugins/libBazaar.so
/usr/lib64/qtcreator/plugins/libBeautifier.so
/usr/lib64/qtcreator/plugins/libBinEditor.so
/usr/lib64/qtcreator/plugins/libBookmarks.so
/usr/lib64/qtcreator/plugins/libBoot2Qt.so
/usr/lib64/qtcreator/plugins/libCMakeProjectManager.so
/usr/lib64/qtcreator/plugins/libCVS.so
/usr/lib64/qtcreator/plugins/libClangCodeModel.so
/usr/lib64/qtcreator/plugins/libClangFormat.so
/usr/lib64/qtcreator/plugins/libClangTools.so
/usr/lib64/qtcreator/plugins/libClassView.so
/usr/lib64/qtcreator/plugins/libClearCase.so
/usr/lib64/qtcreator/plugins/libCodePaster.so
/usr/lib64/qtcreator/plugins/libCompilationDatabaseProjectManager.so
/usr/lib64/qtcreator/plugins/libConan.so
/usr/lib64/qtcreator/plugins/libCore.so
/usr/lib64/qtcreator/plugins/libCppEditor.so
/usr/lib64/qtcreator/plugins/libCppTools.so
/usr/lib64/qtcreator/plugins/libCppcheck.so
/usr/lib64/qtcreator/plugins/libCtfVisualizer.so
/usr/lib64/qtcreator/plugins/libDebugger.so
/usr/lib64/qtcreator/plugins/libDesigner.so
/usr/lib64/qtcreator/plugins/libDiffEditor.so
/usr/lib64/qtcreator/plugins/libDocker.so
/usr/lib64/qtcreator/plugins/libEmacsKeys.so
/usr/lib64/qtcreator/plugins/libFakeVim.so
/usr/lib64/qtcreator/plugins/libGLSLEditor.so
/usr/lib64/qtcreator/plugins/libGenericProjectManager.so
/usr/lib64/qtcreator/plugins/libGit.so
/usr/lib64/qtcreator/plugins/libHelloWorld.so
/usr/lib64/qtcreator/plugins/libHelp.so
/usr/lib64/qtcreator/plugins/libImageViewer.so
/usr/lib64/qtcreator/plugins/libIncrediBuild.so
/usr/lib64/qtcreator/plugins/libIos.so
/usr/lib64/qtcreator/plugins/libLanguageClient.so
/usr/lib64/qtcreator/plugins/libMacros.so
/usr/lib64/qtcreator/plugins/libMarketplace.so
/usr/lib64/qtcreator/plugins/libMcuSupport.so
/usr/lib64/qtcreator/plugins/libMercurial.so
/usr/lib64/qtcreator/plugins/libMesonProjectManager.so
/usr/lib64/qtcreator/plugins/libModelEditor.so
/usr/lib64/qtcreator/plugins/libNim.so
/usr/lib64/qtcreator/plugins/libPerfProfiler.so
/usr/lib64/qtcreator/plugins/libPerforce.so
/usr/lib64/qtcreator/plugins/libProjectExplorer.so
/usr/lib64/qtcreator/plugins/libPython.so
/usr/lib64/qtcreator/plugins/libQbsProjectManager.so
/usr/lib64/qtcreator/plugins/libQmakeProjectManager.so
/usr/lib64/qtcreator/plugins/libQmlDesigner.so
/usr/lib64/qtcreator/plugins/libQmlJSEditor.so
/usr/lib64/qtcreator/plugins/libQmlJSTools.so
/usr/lib64/qtcreator/plugins/libQmlPreview.so
/usr/lib64/qtcreator/plugins/libQmlProfiler.so
/usr/lib64/qtcreator/plugins/libQmlProjectManager.so
/usr/lib64/qtcreator/plugins/libQnx.so
/usr/lib64/qtcreator/plugins/libQtSupport.so
/usr/lib64/qtcreator/plugins/libRemoteLinux.so
/usr/lib64/qtcreator/plugins/libResourceEditor.so
/usr/lib64/qtcreator/plugins/libScxmlEditor.so
/usr/lib64/qtcreator/plugins/libSerialTerminal.so
/usr/lib64/qtcreator/plugins/libSilverSearcher.so
/usr/lib64/qtcreator/plugins/libStudioWelcome.so
/usr/lib64/qtcreator/plugins/libSubversion.so
/usr/lib64/qtcreator/plugins/libTaskList.so
/usr/lib64/qtcreator/plugins/libTextEditor.so
/usr/lib64/qtcreator/plugins/libTodo.so
/usr/lib64/qtcreator/plugins/libUpdateInfo.so
/usr/lib64/qtcreator/plugins/libValgrind.so
/usr/lib64/qtcreator/plugins/libVcsBase.so
/usr/lib64/qtcreator/plugins/libWebAssembly.so
/usr/lib64/qtcreator/plugins/libWelcome.so
/usr/lib64/qtcreator/plugins/libWinRt.so
/usr/lib64/qtcreator/plugins/qbs/plugins/libclangcompilationdbgenerator.so
/usr/lib64/qtcreator/plugins/qbs/plugins/libiarewgenerator.so
/usr/lib64/qtcreator/plugins/qbs/plugins/libkeiluvgenerator.so
/usr/lib64/qtcreator/plugins/qbs/plugins/libmakefilegenerator.so
/usr/lib64/qtcreator/plugins/qbs/plugins/libqbs_cpp_scanner.so
/usr/lib64/qtcreator/plugins/qbs/plugins/libqbs_qt_scanner.so
/usr/lib64/qtcreator/plugins/qbs/plugins/libvisualstudiogenerator.so
/usr/lib64/qtcreator/plugins/qmldesigner/libassetexporterplugin.so
/usr/lib64/qtcreator/plugins/qmldesigner/libcomponentsplugin.so
/usr/lib64/qtcreator/plugins/qmldesigner/libqmlpreviewplugin.so
/usr/lib64/qtcreator/plugins/qmldesigner/libqtquickplugin.so

%files libexec
%defattr(-,root,root,-)
/usr/libexec/qtcreator/buildoutputparser
/usr/libexec/qtcreator/clangbackend
/usr/libexec/qtcreator/cpaster
/usr/libexec/qtcreator/cplusplus-ast2png
/usr/libexec/qtcreator/cplusplus-frontend
/usr/libexec/qtcreator/cplusplus-mkvisitor
/usr/libexec/qtcreator/cplusplus-update-frontend
/usr/libexec/qtcreator/dmgbuild
/usr/libexec/qtcreator/perf2text
/usr/libexec/qtcreator/perfparser
/usr/libexec/qtcreator/qbs_processlauncher
/usr/libexec/qtcreator/qml2puppet
/usr/libexec/qtcreator/qtc-askpass
/usr/libexec/qtcreator/qtcreator_process_stub
/usr/libexec/qtcreator/qtpromaker
/usr/libexec/qtcreator/sdktool
